# Generated by Django 5.1 on 2024-09-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Oportunidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("estagio", "Estágio"),
                            ("trabalho", "Trabalho"),
                            ("voluntario", "Voluntário"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "numero_contato",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "email_contato",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "quantia_vagas",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("is_remunerado", models.BooleanField(default=False)),
                ("remuneracao", models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                "verbose_name": "Oportunidade",
                "verbose_name_plural": "Oportunidades",
            },
        ),
    ]
