# Generated by Django 5.1 on 2024-09-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag'),
        ('oportunidades', '0001_initial'),
        ('universidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('requisitos', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='universidades.curso'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.tag'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='tipo_trabalho',
            field=models.CharField(choices=[('home_office', 'Home Office'), ('presencial', 'Presencial'), ('hibrido', 'Hibrido')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='areas',
            field=models.ManyToManyField(blank=True, to='oportunidades.area'),
        ),
    ]
