# Generated by Django 5.1 on 2024-09-03 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('oportunidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='beneficios_oportunidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='requisitos_envio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.requisito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='requisitos_oportunidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='tipo',
            field=models.CharField(choices=[('EST', 'Estágio'), ('TRA', 'Trabalho'), ('VOL', 'Voluntariado'), ('BOL', 'Bolsa')], default='', max_length=3),
        ),
    ]
