# Generated by Django 5.1 on 2024-09-02 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0002_area_oportunidade_cursos_oportunidade_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 2, 15, 26, 13, 35870, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
