# Generated by Django 5.1 on 2024-09-02 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0003_oportunidade_criado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoOportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precisa_curriculo', models.BooleanField(default=False)),
                ('precisa_descricao', models.BooleanField(default=False)),
                ('precisa_email_contato', models.BooleanField(default=False)),
                ('precisa_telefone_contato', models.BooleanField(default=False)),
                ('precisa_endereco', models.BooleanField(default=False)),
                ('curriculo', models.FileField(blank=True, null=True, upload_to='curriculos/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone_contato', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Requisito Oportunidade',
                'verbose_name_plural': 'Requisitos das Oportunidades',
            },
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='requisito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oportunidades.requisitooportunidade'),
        ),
    ]
