# Generated by Django 5.1 on 2024-09-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_requisitooportunidade_solicitacao_curriculo_and_more'),
        ('oportunidades', '0004_requisitooportunidade_oportunidade_requisito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidade',
            name='requisito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.requisitooportunidade'),
        ),
        migrations.DeleteModel(
            name='RequisitoOportunidade',
        ),
    ]
