# Generated by Django 5.1 on 2024-09-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField(blank=True, null=True)),
                ("local", models.CharField(blank=True, max_length=255, null=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("ativo", models.BooleanField(default=True)),
                ("is_pago", models.BooleanField(default=False)),
                ("valor_entrada", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
    ]
