# Generated by Django 5.1 on 2024-09-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.tag'),
        ),
    ]
