# Generated by Django 5.1 on 2024-09-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_requisitooportunidade_solicitacao_curriculo_and_more'),
        ('eventos', '0002_evento_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='requisito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.requisitooportunidade'),
        ),
    ]
