# Generated by Django 4.2.13 on 2024-07-23 20:17

from django.db import migrations, models

from voalle_ia.settings import PERMITE_MIGRATE


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "People",
                "verbose_name_plural": "People",
                "db_table": "people",
                "managed": PERMITE_MIGRATE,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("active", models.BooleanField()),
                ("omnichannel_attendance_limit", models.BigIntegerField()),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "managed": PERMITE_MIGRATE,
            },
        ),
    ]
