# Generated by Django 5.1 on 2024-09-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='respostas_arquivos/')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precisa_texto', models.BooleanField(default=False)),
                ('helptext_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('precisa_arquivos', models.BooleanField(default=False)),
                ('helptext_arquivos', models.CharField(blank=True, max_length=200, null=True)),
                ('precisa_foto', models.BooleanField(default=False)),
                ('helptext_foto', models.CharField(blank=True, max_length=200, null=True)),
                ('precisa_links', models.BooleanField(default=False)),
                ('helptext_links', models.CharField(blank=True, max_length=200, null=True)),
                ('precisa_checkbox', models.BooleanField(default=False)),
                ('helptext_checkbox', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
            },
        ),
        migrations.CreateModel(
            name='RespostaRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('links', models.URLField(blank=True, null=True)),
                ('checkbox', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Resposta de Requisito',
                'verbose_name_plural': 'Respostas de Requisitos',
            },
        ),
    ]
