# Generated by Django 5.1 on 2024-09-02 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("oportunidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Arquivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(upload_to="arquivos/")),
            ],
            options={
                "verbose_name": "Arquivo",
                "verbose_name_plural": "Arquivos",
            },
        ),
        migrations.CreateModel(
            name="Solicitacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("estagio", "Estágio"),
                            ("trabalho", "Trabalho"),
                            ("evento", "Evento"),
                            ("voluntario", "Voluntário"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                ("respondida", models.BooleanField(default=False)),
                ("texto", models.TextField(blank=True, null=True)),
                (
                    "oportunidade_referente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oportunidades.oportunidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação",
                "verbose_name_plural": "Solicitações",
            },
        ),
    ]
