# Generated by Django 5.1 on 2024-09-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precisa_texto', models.BooleanField(default=False)),
                ('precisa_arquivos', models.BooleanField(default=False)),
                ('precisa_foto', models.BooleanField(default=False)),
                ('precisa_links', models.BooleanField(default=False)),
                ('precisa_checkbox', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
            },
        ),
    ]
