# Generated by Django 5.1 on 2024-09-04 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('oportunidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesse',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oportunidades.oportunidade'),
        ),
        migrations.AddField(
            model_name='respostarequisito',
            name='arquivos',
            field=models.ManyToManyField(blank=True, related_name='respostas_requisitos', to='core.arquivo'),
        ),
        migrations.AddField(
            model_name='respostarequisito',
            name='requisito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.requisito'),
        ),
    ]
