# Generated by Django 5.1 on 2024-09-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_tag', models.CharField(choices=[('por_curso', 'Por Curso'), ('por_cidade', 'Por Cidade'), ('por_universidade', 'Por Universidade'), ('por_area', 'Por Area'), ('por_tipo_trabalho', 'Por Trabalho'), ('por_tipo_oportunidade', 'Por Oportunidade')], default='', max_length=100)),
                ('nome_relacionado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
