# Generated by Django 5.1 on 2024-09-04 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='respostarequisito',
            name='respondido_empresa',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RespostaInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.interesse')),
                ('respondido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resposta de Interesse',
                'verbose_name_plural': 'Respostas de Interesses',
            },
        ),
    ]
