# Generated by Django 5.1 on 2024-09-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universidades', '0002_estado_uf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaatuacao',
            options={'verbose_name': 'Área de Atuação', 'verbose_name_plural': 'Áreas de Atuação'},
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='universidade',
            options={'verbose_name': 'Universidade', 'verbose_name_plural': 'Universidades'},
        ),
    ]
