# Generated by Django 5.1 on 2024-09-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidades', '0003_alter_areaatuacao_options_alter_cidade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='areas_atuacao',
            field=models.ManyToManyField(related_name='areas_atuacao_curso', to='universidades.areaatuacao'),
        ),
    ]
