# Generated by Django 5.1 on 2024-09-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_empresa',
            field=models.BooleanField(default=False),
        ),
    ]
