# Generated by Django 5.1 on 2024-09-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_is_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_empresa',
            new_name='pertence_empresa',
        ),
        migrations.AddField(
            model_name='usuario',
            name='pertence_universidade',
            field=models.BooleanField(default=False),
        ),
    ]
